

PRAGMA foreign_keys = ON;

--

DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE
);

--

DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    join_date DATE DEFAULT CURRENT_DATE
);

--

DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    price INTEGER NOT NULL CHECK (price >= 0),
    published_date DATE,
    category_id INTEGER,
    FOREIGN KEY (category_id) REFERENCES CATEGORY(id) ON DELETE RESTRICT
);

--

DROP TABLE IF EXISTS RENTAL;

CREATE TABLE RENTAL(
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    member_id INTEGER NOT NULL,
    book_id INTEGER NOT NULL,

    rental_date DATE NOT NULL DEFAULT CURRENT_DATE,

    return_date DATE,

    status VARCHAR(20) NOT NULL DEFAULT 'RENTED' CHECK (status IN ('RENTED', 'RETURNED', 'OVERDUE')),

    FOREIGN KEY (member_id) REFERENCES MEMBER(id) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES BOOK(id) ON DELETE RESTRICT

);